php_error_reporting: 'E_ALL'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_track_errors: 'On'
php_mysqlnd_collect_memory_statistics: 'On'
php_opcache_enable: 0

xdebug_remote_enable: 1
xdebug_remote_connect_back: 1
xdebug_remote_host: 10.0.2.2
xdebug_remote_port: 9000
xdebug_max_nesting_level: 512
xdebug_remote_autostart: true
xdebug_remote_log: /var/log/xdebug.log