# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  neudrum.com.au:
    site_hosts:
      - canonical: neudrumold.test
        redirects:
          - www.neudrumold.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: angusdowling@live.com.au
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
